# This is a basic workflow to help you get started with Actions

name: ayuda-en-python-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute main py script
        run: python main.py
      - name: commit and push
        run: |
          git commit -am "update: readme"
          git push
